import 'normalize.css'
import './custom-bootstrap-grid/bootstrap.scss'
import './print-fix.css'
import '../components/bootstrap3/bootstrap.min.js'
import '../components/prototype-extensions.js'
import '../components/animations/paths.js'
import './angular-tools'
